### ISSUE TITLE
Please provide Grok Pattern for the output

### ISSUE THREAD

**Issue by ibmdcb** [pivotal-cf/fluent-bit-out-syslog#21] opened 2018-12-18 21:24 UTC
Would be much appreciated. Could someone Please? 

We are sinking syslog to ELK. Logstash got the following message. Now we would really like to parse it to get metadata such as container_name and namespace_name. For that we need a grok pattern. I am going to spend the next coming days trying to figure out how to do it, but since you all generated the output, not in yaml or json, why don't you guys help to parse it, especially since you guys are likely much better with grok than I am.

Thank you! 

302 <14>1 2018-12-18T19:00:09.493606+00:00 61bb6eae-7802-4870-814b-5a77e1917989 kube-system/tcp-route-registrar-master-9f69b4bc9 - - [kubernetes@47450 namespace_name=\"kube-system\" object_name=\"tcp-route-registrar-master-9f69b4bc9-h9dm9\" container_name=\"tcp-route-registrar-master\"] registered route

**Comment by ahevenor** [comment] 2018-12-18 21:35
@ibmdcb we are actually not experts on ELK/EFK as this plugin can be used for a wide variety of log storage systems. I can confirm that we provide the namespace and container name, both in the program field and in the structured data portions of the message - so you _should_ be able to parse this. 

Closing this since we can't really help with Grok syntax.

**Closed by ahevenor** 2018-12-18 21:35 UTC
Labels: unscheduled

**Comment by jasonkeene** [comment] 2018-12-19 16:51
@ibmdcb Just a heads up we are not writing unstructured text. The information you are interested in is part of the "structured data" section of an [RFC5424][RFC5424] message. If you are using an RFC 5424 message parser you should not have to use regex to extract this information.

[RFC5424]: https://tools.ietf.org/html/rfc5424#section-6.3

**Comment by ibmdcb** [comment] 2018-12-20 20:30
@jasonkeene Indeed there is an existing rfc5424 parser for grok called SYSLOG5424LINE. Now this all makes sense and is elegant. Thank you so much!

```
      grok {
        match => { "message" => "%{SYSLOG5424LINE}" }
      }
      if [syslog5424_sd] {
        # All structured data needs to be in format [key=value,key=value,...]
        mutate {
          # Remove wrapping brackets
          gsub => [ "syslog5424_sd", "[\[\]]", "" ]
        }
        kv {
          # Convert the structured data into Logstash fields
          source => "syslog5424_sd"
          field_split => " "
          value_split => "="
          remove_field => [ "syslog5424_sd" ]
        }
      }

```
